# 1.全连接层：正向传播，随机初始化w，b

In [2]:
# 全连接层：正向传播
import numpy as np
x = np.arange(1,11,1).reshape(2,5)
print ("上层输出是2个batch，每个batch有5个向量：\n" + str(x))

std = 1e-4
ww = std * np.random.randn(5,3)
bb = std * np.zeros(3)
print ("\n随机初始化w的参数的shape是：\n" + str(ww.shape))
print ("\n随机初始化w的参数是：\n" + str(ww))
print ("\n随机初始化b的参数的shape是：\n" + str(bb.shape))
print ("\n随机初始化b的参数是：\n" + str(bb))
a = x.dot(ww) + bb
print ("\n全连接之后输出层的shape是：\n" + str(a.shape))
print ("\n全连接之后输出是：\n" + str(a))



上层输出是2个batch，每个batch有5个向量：
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

随机初始化w的参数的shape是：
(5, 3)

随机初始化w的参数是：
[[  8.94771561e-05   1.79349165e-05  -1.45893465e-04]
 [  2.03269312e-04   3.02177958e-04   9.09080278e-05]
 [  1.18603291e-05  -5.41043823e-05  -1.01244815e-04]
 [ -1.36838714e-04  -2.23499705e-04  -7.65339667e-05]
 [ -4.10437478e-05   6.55004715e-05  -7.37103695e-05]]

随机初始化b的参数的shape是：
(3,)

随机初始化b的参数是：
[ 0.  0.  0.]

全连接之后输出层的shape是：
(2, 3)

全连接之后输出是：
[[-0.00022098 -0.00010652 -0.0009425 ]
 [ 0.00041264  0.00043353 -0.00247487]]


# 2.全连接，反向传播

In [3]:
# 1.对上一层的输出（即当前层的输入）求导
loss = np.arange(0,1.2,0.2).reshape(2,3)
print ("假设下层传过来的loss是：\n" + str(loss))
residual_x = loss.dot(ww.T)
print ("\n1.对上层的输出求导值的shape：\n" + str(residual_x.shape))
print ("\n对上层的输出求导：\n" + str(residual_x))



# 2.对权重系数W求导
lr = 0.01
reg = 0.75
prev_grad_w = np.zeros_like(ww)
ww -=  lr * (x.T.dot(loss) + prev_grad_w * reg)
prev_grad_w = ww

print ("\n2.对权重系数W求导之后更新的W值的shape：\n" + str(prev_grad_w.shape))
print ("\n对权重系数W求导之后更新的W：\n" + str(prev_grad_w))

# 3.对偏置系数b求导
prev_grad_b = np.zeros_like(bb)
bb -= lr * (np.sum(loss, axis=0))
prev_grad_b = bb

print ("\n3.对偏置系数b求导之后更新的b值的shape：\n" + str(prev_grad_b.shape))
print ("\n对偏置系数b求导之后更新的b：\n" + str(prev_grad_b))

假设下层传过来的loss是：
[[ 0.   0.2  0.4]
 [ 0.6  0.8  1. ]]

1.对上层的输出求导值的shape：
(2, 5)

对上层的输出求导：
[[ -5.47704027e-05   9.67988027e-05  -5.13188025e-05  -7.53135276e-05
   -1.63840535e-05]
 [ -7.78592381e-05   4.54611981e-04  -1.37412123e-04  -3.37436959e-04
   -4.59362410e-05]]

2.对权重系数W求导之后更新的W值的shape：
(5, 3)

对权重系数W求导之后更新的W：
[[-0.03591052 -0.04998207 -0.06414589]
 [-0.04179673 -0.05969782 -0.07790909]
 [-0.04798814 -0.0700541  -0.09210124]
 [-0.05413684 -0.0802235  -0.10607653]
 [-0.06004104 -0.0899345  -0.12007371]]

3.对偏置系数b求导之后更新的b值的shape：
(3,)

对偏置系数b求导之后更新的b：
[-0.006 -0.01  -0.014]


# 3.numpy 的flatten层：将每个batch里的每个channel按顺序按行展开

In [4]:
# numpy 的flatten层：将每个batch里的每个channel安顺序按行展开
import numpy as np
q = np.arange(1,25,1).reshape(2,3,2,2)
print (q)
print (q.reshape(2,3*2*2))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]]

  [[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [5]:
import numpy as np
cc = np.arange(0,1,0.1).reshape(2,5)
dd = np.ones(10).reshape(2,5)*5
print (cc)
print (dd)
print (cc>0)
print ((cc>0)*dd)

[[ 0.   0.1  0.2  0.3  0.4]
 [ 0.5  0.6  0.7  0.8  0.9]]
[[ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]]
[[False  True  True  True  True]
 [ True  True  True  True  True]]
[[ 0.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]]


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])