# 1. python（类和对象之保存数据到本地）

In [1]:
#声明一个类型
class People(object):
    #类变量
    file_name = 'student.txt'
    def __init__(self,name,school):
        self.name = name
        self.school = school
        #属性可以是列表
        self.pdc = []
        #属性也可以是字典
        self.pdc_dict = {}
    #保存数据的函数
    def save_data(self):
        #1.打开文件
        f = open(self.file_name,'a',encoding='utf-8')
        #2.写入数据
        f.write(self.name)
        f.write(';')
        f.write(self.school)
        f.write('\n---->')
        #将所有的前任名称拼接成一个字符串
        pdc_str = ' '.join(self.pdc)
        f.write(pdc_str)
        f.write('\n')
        #3.关闭文件
        f.close()
People.file_name = 'stu.txt'
#创建一个People对象
#对象有保存信息到本地的函数
p1 = People('张三','智游')
# p1.save_data()
p2 = People('李四','智游')
# p1.save_data()
# 获取对象的属性值，这个属性值是一个列表
p1.pdc.append(p2.name)
print(p1.pdc)
 
p3 = People('豆豆','智游')
# p1.pdc是一个列表，列表的增删改查都可以正常操作
p1.pdc.append(p3.name)
print(p1.pdc)
# 遍历p1的所有前任名称
for name in p1.pdc:
    print(name)
p1.save_data()

['李四']
['李四', '豆豆']
李四
豆豆


# 2.类变量传递？（需要再看）

In [15]:
class Test(object):  
    num_of_instance = 0  
    def __init__(self, name):  
        self.name = name  #实例变量
        self.w = 10
        Test.num_of_instance += 1 #类变量 
    def ok(self):
        w = 100
  
if __name__ == '__main__':  
    print (Test.num_of_instance)  
    t1 = Test('jack')  
    print (Test.num_of_instance)  
    t2 = Test('lucy')
  
   
    print (t1.name , t1.num_of_instance,t1.w,)  
    print (t2.name , t2.num_of_instance)

0
1
jack 3 10
lucy 3


# bool变量的计算

In [14]:
import numpy as np
print (np.ones(9))
print (np.zeros(9))
print (np.arange(9))
a = np.ones(9)==np.zeros(9)
b = np.arange(9)==np.zeros(9)
print (a)
c = np.sum(np.ones(9)==np.zeros(9))
d = np.sum(np.arange(9)==np.zeros(9))
print (c)
print (d)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
[0 1 2 3 4 5 6 7 8]
[False False False False False False False False False]
0
1


# list的append

In [26]:
#!/usr/bin/python

aList = []
aList.append( 2009 )
aList = [123, 'xyz', 'zara', 'abc']
aList.append( 2009 )
print ("Updated List : ", aList)
print (len(aList))

Updated List :  [123, 'xyz', 'zara', 'abc', 2009]
5


# 使用pickle增量存取数组，list等


In [125]:
import pickle
data1 = np.arange(9).reshape(3,3)
data2 = np.arange(8).reshape(2,4)

output = open('./data.pkl', 'wb')

# Pickle dictionary using protocol 0.
pickle.dump(data1, output)
pickle.dump(data2, output)

output.close()

In [137]:
import pickle

pkl_file = open('./data.pkl', 'rb')

for i in range(0,2):                #注意：pickle存储可以增量存储，但是读取时不是一下子读出来的，而是按顺序一个一个读取        
    data_pkl = pickle.load(pkl_file)
    print(data_pkl)
    print ("\n")

pkl_file.close()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2 3]
 [4 5 6 7]]




# 数组与list相互转换

In [124]:
#a为python的list类型
a=([3.234,34,3.777,6.33])

# list 用len（a）查看长度
print(len(a))

#将a转化为numpy的array:  
print (np.array(a))

# c 是array
c = np.array([  3.234,  34.   ,   3.777,   6.33 ])


#将a转化为python的list
print (len(c.tolist()))

4
[  3.234  34.      3.777   6.33 ]
4


In [11]:
import numpy as np
a = np.arange(9).reshape(1,1,3,3)
print (a)
print (a.shape)

[[[[0 1 2]
   [3 4 5]
   [6 7 8]]]]
(1, 1, 3, 3)
